---
title: "Metrics and Stats"
author: 'By: Claire Gonzales'
date: '2022-07-21'
output: 
  html_document: 
    theme: lumen
    code_folding: hide
---

### Description

**OBJECTIVE**: The objective for this script is to create descriptive metric and stats from the original data csv file. These values will be useful for table creation and in-text descriptions 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
	message = FALSE,
	warning = FALSE)

library(tidyverse)
library(here)

```

### Reading in Data

```{r}
mydata <- read_csv(here("data", "Data_total_working_for_r.csv"))
```


```{r}
mydata_sub <- mydata %>% 
  select(year, id, ecology, governance, socioecon, aquaculture_present, wind_present, wave_present, tidal_present, other_present)

```


### Wrangling

```{r}

# creating totals for each discipline

discipline_eco <- mydata_sub %>% 
  group_by(ecology) %>% 
  filter(ecology == 1) %>% 
  summarize(sum = sum(ecology))

discipline_gov <- mydata_sub %>%
  group_by(governance) %>% 
  filter(governance == 1) %>% 
  summarize(sum = sum(governance))

discipline_socio <- mydata_sub %>%
  group_by(socioecon) %>% 
  filter(socioecon == 1) %>% 
  summarize(sum = sum(socioecon))
  
```


```{r}

names <- c("ecology", "governance", "socioeconomics")
sum <- c(discipline_eco$sum, discipline_gov$sum, discipline_socio$sum)

discipline <- data.frame(cbind(names, sum))
```


```{r}
# creating totals for each tyoe of ocean activity present

act_aqua <- mydata_sub %>% 
  group_by(aquaculture_present) %>% 
  filter(aquaculture_present == 1) %>% 
  summarize(sum = sum(aquaculture_present))

act_wind <- mydata_sub %>% 
  group_by(wind_present) %>% 
  filter(wind_present == 1) %>% 
  summarize(sum = sum(wind_present))
  
act_wave <- mydata_sub %>% 
  group_by(wave_present) %>% 
  filter(wave_present == 1) %>% 
  summarize(sum = sum(wave_present))

act_tidal <- mydata_sub %>% 
  group_by(tidal_present) %>% 
  filter(tidal_present == 1) %>% 
  summarize(sum = sum(tidal_present))

act_other <- mydata_sub %>% 
  group_by(other_present) %>% 
  filter(other_present == 1) %>% 
  summarize(sum = sum(other_present))

```

```{r}
act_names <- c("aquaculture", "tidal", "wave", "wind", "other")

sums <- c(act_aqua$sum, act_tidal$sum, act_wave$sum, act_wind$sum, act_other$sum)

activity <- data.frame(cbind(act_names, sums))
```

